micronaut:
  application:
    name: order-service

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000



jpa:
  default:
    packages-to-scan:
      - 'order.service'
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true

kafka:
  bootstrap:
    servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"
  producers:
        default:
            retries: 5