micronaut:
  application:
    name: order-service

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:admin}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000

#export JDBC_URL=jdbc:postgresql://localhost:5432/micronaut
#export JDBC_USER=dbuser
#export JDBC_PASSWORD=theSecretPassword
#export JDBC_DRIVER=org.postgresql.Driver

jpa:
  default:
    packages-to-scan:
      - 'example.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true